### ISSUE TITLE
Is kraken2OTU available for bracken outputs？

### ISSUE THREAD

**Issue by Fishball99** [sipost1/kraken2OTUtable#3]
Since bracken's outputs are more reliable than kraken's, I want to use bracken's outputs to convert to OTU table

**Comment by sipost1** [comment]
Hi!

Yes, it also works with bracken report, as the format is seemingly the same as kraken2's report format. I tested it on [this file](https://github.com/jenniferlu717/Bracken/blob/master/sample_data/sample_output_bracken.report).

**Comment by Fishball99** [comment]
Thanks a lot, I'll try for it once gitclone done.
